language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "sudo apt-get install fakeroot"
  - "mount"
  - "sudo mount /home/travis -o remount,user_xattr"
  - "pip install --use-mirrors Cython"
  - "pip install -e ."
# command to run tests
script: fakeroot python -m darc.testsuite.run -vb
